// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using netxml2kml.Data;

#nullable disable

namespace netxml2kml.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220810152156_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("netxml2kml.Models.WirelessClient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mac")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPackets")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WirelessClients");
                });

            modelBuilder.Entity("netxml2kml.Models.WirelessNetwork", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bssid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Channel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Encryption")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("TEXT");

                    b.Property<int>("FrequencyMhz")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsCloaked")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxAltitude")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxLatitude")
                        .HasColumnType("REAL");

                    b.Property<double>("MaxLongitude")
                        .HasColumnType("REAL");

                    b.Property<int>("MaxSignalDbm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ssid")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalPackets")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WirelessClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WirelessClientId");

                    b.ToTable("WirelessNetworks");
                });

            modelBuilder.Entity("netxml2kml.Models.WirelessNetwork", b =>
                {
                    b.HasOne("netxml2kml.Models.WirelessClient", "WirelessClient")
                        .WithMany()
                        .HasForeignKey("WirelessClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WirelessClient");
                });
#pragma warning restore 612, 618
        }
    }
}
