//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated

// 
//This source code was auto-generated by MonoXSD
//
namespace netxml2kml.Models {
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class packets {
        
        private string lLCField;
        
        private string dataField;
        
        private string cryptField;
        
        private string totalField;
        
        private string fragmentsField;
        
        private string retriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LLC {
            get {
                return this.lLCField;
            }
            set {
                this.lLCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string crypt {
            get {
                return this.cryptField;
            }
            set {
                this.cryptField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string total {
            get {
                return this.totalField;
            }
            set {
                this.totalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string fragments {
            get {
                return this.fragmentsField;
            }
            set {
                this.fragmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string retries {
            get {
                return this.retriesField;
            }
            set {
                this.retriesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("snr-info", Namespace="", IsNullable=false)]
    public partial class snrinfo {
        
        private string last_signal_dbmField;
        
        private string last_noise_dbmField;
        
        private string last_signal_rssiField;
        
        private string last_noise_rssiField;
        
        private string min_signal_dbmField;
        
        private string min_noise_dbmField;
        
        private string min_signal_rssiField;
        
        private string min_noise_rssiField;
        
        private string max_signal_dbmField;
        
        private string max_noise_dbmField;
        
        private string max_signal_rssiField;
        
        private string max_noise_rssiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_signal_dbm {
            get {
                return this.last_signal_dbmField;
            }
            set {
                this.last_signal_dbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_noise_dbm {
            get {
                return this.last_noise_dbmField;
            }
            set {
                this.last_noise_dbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_signal_rssi {
            get {
                return this.last_signal_rssiField;
            }
            set {
                this.last_signal_rssiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_noise_rssi {
            get {
                return this.last_noise_rssiField;
            }
            set {
                this.last_noise_rssiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string min_signal_dbm {
            get {
                return this.min_signal_dbmField;
            }
            set {
                this.min_signal_dbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string min_noise_dbm {
            get {
                return this.min_noise_dbmField;
            }
            set {
                this.min_noise_dbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string min_signal_rssi {
            get {
                return this.min_signal_rssiField;
            }
            set {
                this.min_signal_rssiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string min_noise_rssi {
            get {
                return this.min_noise_rssiField;
            }
            set {
                this.min_noise_rssiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string max_signal_dbm {
            get {
                return this.max_signal_dbmField;
            }
            set {
                this.max_signal_dbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string max_noise_dbm {
            get {
                return this.max_noise_dbmField;
            }
            set {
                this.max_noise_dbmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string max_signal_rssi {
            get {
                return this.max_signal_rssiField;
            }
            set {
                this.max_signal_rssiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string max_noise_rssi {
            get {
                return this.max_noise_rssiField;
            }
            set {
                this.max_noise_rssiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("gps-info", Namespace="", IsNullable=false)]
    public partial class gpsinfo {
        
        private string minlatField;
        
        private string minlonField;
        
        private string minaltField;
        
        private string minspdField;
        
        private string maxlatField;
        
        private string maxlonField;
        
        private string maxaltField;
        
        private string maxspdField;
        
        private string peaklatField;
        
        private string peaklonField;
        
        private string peakaltField;
        
        private string avglatField;
        
        private string avglonField;
        
        private string avgaltField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-lat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minlat {
            get {
                return this.minlatField;
            }
            set {
                this.minlatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-lon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minlon {
            get {
                return this.minlonField;
            }
            set {
                this.minlonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-alt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minalt {
            get {
                return this.minaltField;
            }
            set {
                this.minaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("min-spd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string minspd {
            get {
                return this.minspdField;
            }
            set {
                this.minspdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-lat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxlat {
            get {
                return this.maxlatField;
            }
            set {
                this.maxlatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-lon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxlon {
            get {
                return this.maxlonField;
            }
            set {
                this.maxlonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-alt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxalt {
            get {
                return this.maxaltField;
            }
            set {
                this.maxaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-spd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxspd {
            get {
                return this.maxspdField;
            }
            set {
                this.maxspdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("peak-lat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string peaklat {
            get {
                return this.peaklatField;
            }
            set {
                this.peaklatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("peak-lon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string peaklon {
            get {
                return this.peaklonField;
            }
            set {
                this.peaklonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("peak-alt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string peakalt {
            get {
                return this.peakaltField;
            }
            set {
                this.peakaltField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avg-lat", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avglat {
            get {
                return this.avglatField;
            }
            set {
                this.avglatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avg-lon", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avglon {
            get {
                return this.avglonField;
            }
            set {
                this.avglonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("avg-alt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string avgalt {
            get {
                return this.avgaltField;
            }
            set {
                this.avgaltField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute("detection-run", Namespace="", IsNullable=false)]
    public partial class detectionrun {
        
        private detectionrunWirelessnetwork[] wirelessnetworkField;
        
        private string kismetversionField;
        
        private string starttimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wireless-network", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public detectionrunWirelessnetwork[] wirelessnetwork {
            get {
                return this.wirelessnetworkField;
            }
            set {
                this.wirelessnetworkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("kismet-version")]
        public string kismetversion {
            get {
                return this.kismetversionField;
            }
            set {
                this.kismetversionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("start-time")]
        public string starttime {
            get {
                return this.starttimeField;
            }
            set {
                this.starttimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detectionrunWirelessnetwork {
        
        private string bSSIDField;
        
        private string manufField;
        
        private string channelField;
        
        private string freqmhzField;
        
        private string maxseenrateField;
        
        private string carrierField;
        
        private string encodingField;
        
        private string datasizeField;
        
        private string bsstimestampField;
        
        private string cdpdeviceField;
        
        private string cdpportidField;
        
        private detectionrunWirelessnetworkSSID[] sSIDField;
        
        private packets[] packetsField;
        
        private detectionrunWirelessnetworkWirelessclient[] wirelessclientField;
        
        private snrinfo[] snrinfoField;
        
        private gpsinfo[] gpsinfoField;
        
        private string numberField;
        
        private string typeField;
        
        private string firsttimeField;
        
        private string lasttimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSSID {
            get {
                return this.bSSIDField;
            }
            set {
                this.bSSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string manuf {
            get {
                return this.manufField;
            }
            set {
                this.manufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string freqmhz {
            get {
                return this.freqmhzField;
            }
            set {
                this.freqmhzField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxseenrate {
            get {
                return this.maxseenrateField;
            }
            set {
                this.maxseenrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string datasize {
            get {
                return this.datasizeField;
            }
            set {
                this.datasizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bsstimestamp {
            get {
                return this.bsstimestampField;
            }
            set {
                this.bsstimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cdp-device", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cdpdevice {
            get {
                return this.cdpdeviceField;
            }
            set {
                this.cdpdeviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cdp-portid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cdpportid {
            get {
                return this.cdpportidField;
            }
            set {
                this.cdpportidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SSID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public detectionrunWirelessnetworkSSID[] SSID {
            get {
                return this.sSIDField;
            }
            set {
                this.sSIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("packets")]
        public packets[] packets {
            get {
                return this.packetsField;
            }
            set {
                this.packetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("wireless-client", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public detectionrunWirelessnetworkWirelessclient[] wirelessclient {
            get {
                return this.wirelessclientField;
            }
            set {
                this.wirelessclientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("snr-info")]
        public snrinfo[] snrinfo {
            get {
                return this.snrinfoField;
            }
            set {
                this.snrinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gps-info")]
        public gpsinfo[] gpsinfo {
            get {
                return this.gpsinfoField;
            }
            set {
                this.gpsinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("first-time")]
        public string firsttime {
            get {
                return this.firsttimeField;
            }
            set {
                this.firsttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("last-time")]
        public string lasttime {
            get {
                return this.lasttimeField;
            }
            set {
                this.lasttimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detectionrunWirelessnetworkSSID {
        
        private string typeField;
        
        private string maxrateField;
        
        private string packetsField;
        
        private string beaconrateField;
        
        private detectionrunWirelessnetworkSSIDEncryption[] encryptionField;
        
        private detectionrunWirelessnetworkSSIDEssid[] essidField;
        
        private string firsttimeField;
        
        private string lasttimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("max-rate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxrate {
            get {
                return this.maxrateField;
            }
            set {
                this.maxrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string packets {
            get {
                return this.packetsField;
            }
            set {
                this.packetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string beaconrate {
            get {
                return this.beaconrateField;
            }
            set {
                this.beaconrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("encryption", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public detectionrunWirelessnetworkSSIDEncryption[] encryption {
            get {
                return this.encryptionField;
            }
            set {
                this.encryptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("essid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public detectionrunWirelessnetworkSSIDEssid[] essid {
            get {
                return this.essidField;
            }
            set {
                this.essidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("first-time")]
        public string firsttime {
            get {
                return this.firsttimeField;
            }
            set {
                this.firsttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("last-time")]
        public string lasttime {
            get {
                return this.lasttimeField;
            }
            set {
                this.lasttimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detectionrunWirelessnetworkSSIDEncryption {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detectionrunWirelessnetworkSSIDEssid {
        
        private string cloakedField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string cloaked {
            get {
                return this.cloakedField;
            }
            set {
                this.cloakedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class detectionrunWirelessnetworkWirelessclient {
        
        private string clientmacField;
        
        private string clientmanufField;
        
        private string channelField;
        
        private string maxseenrateField;
        
        private string carrierField;
        
        private string encodingField;
        
        private packets[] packetsField;
        
        private snrinfo[] snrinfoField;
        
        private gpsinfo[] gpsinfoField;
        
        private string numberField;
        
        private string typeField;
        
        private string firsttimeField;
        
        private string lasttimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("client-mac", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientmac {
            get {
                return this.clientmacField;
            }
            set {
                this.clientmacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("client-manuf", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string clientmanuf {
            get {
                return this.clientmanufField;
            }
            set {
                this.clientmanufField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string channel {
            get {
                return this.channelField;
            }
            set {
                this.channelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string maxseenrate {
            get {
                return this.maxseenrateField;
            }
            set {
                this.maxseenrateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string carrier {
            get {
                return this.carrierField;
            }
            set {
                this.carrierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string encoding {
            get {
                return this.encodingField;
            }
            set {
                this.encodingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("packets")]
        public packets[] packets {
            get {
                return this.packetsField;
            }
            set {
                this.packetsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("snr-info")]
        public snrinfo[] snrinfo {
            get {
                return this.snrinfoField;
            }
            set {
                this.snrinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("gps-info")]
        public gpsinfo[] gpsinfo {
            get {
                return this.gpsinfoField;
            }
            set {
                this.gpsinfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("first-time")]
        public string firsttime {
            get {
                return this.firsttimeField;
            }
            set {
                this.firsttimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("last-time")]
        public string lasttime {
            get {
                return this.lasttimeField;
            }
            set {
                this.lasttimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class NewDataSet {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("detection-run", typeof(detectionrun))]
        [System.Xml.Serialization.XmlElementAttribute("gps-info", typeof(gpsinfo))]
        [System.Xml.Serialization.XmlElementAttribute("packets", typeof(packets))]
        [System.Xml.Serialization.XmlElementAttribute("snr-info", typeof(snrinfo))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
}